### ISSUE TITLE
I run your code on various dataset and get results quite different from your paper's

### ISSUE THREAD

**Issue by 1004766790** [Mrz-zz/MORN#2]
I run the code and get the Property Prediction Performance results following: 
clintox 91.5 
bace 82.3  
tox21 71.5 
bbbp 70.7
They are quite different from those figures in your paper which are following:
clintox 93.9+-0.9
bace 85.8+-0.9
tox21 84.3+-0.4
bbbp 73.8+-1.0
As you only provide the default config for iron dataset, could you provide  the config/parameters for each dataset?

**Comment by mrzzmrzz** [comment]
Hey, I observed that the results for Tox21 are significantly worse compared to what the paper presents. This situation seems abnormal.

The paper provides specific parameter settings for Tox21 in the ablation experiments. I hope this will be helpful for your current experiments.

The parameter settings for the experimental results in the paper were determined through grid search. Due to the extended time since then, the experimental settings for each dataset were not saved due to the migration of the experimental environment. I am sorry for any inconvenience caused.

**Comment by 1004766790** [comment]
Thanks for your prompt reply.

I have seen that the grid search only searches the parameters: "lr" and "alpha" for the best results for each dataset, but there are other parameters like:

clfu_config = {
    "dim_in": 64,
    "dim_hid": 128,
    "mlp_config": {
        "layer_num": 2,
        # after the dim_hid
        "input_dim": 128,
        "hidden_dim": 256,
        "output_dim": num_tasks,
        "dropout_rate": 0.2,
    },
}

The default dataset of "config.py" is iron. So if I want to get the best results on each dataset, the default "config.py" can't support these experiments and I need to conduct parameter tuning?

**Comment by mrzzmrzz** [comment]
Yes, I believe it's still necessary for you to adjust the parameters. Meanwhile, these datasets are relatively small, and our data were divided using different random seeds. Despite taking the mean of three experiments, there is still unavoidable error, so the standard deviation of the experiment results will fluctuate accordingly. For more specific reasons, you can refer to the MoleculeNet paper.
